name: update-stats
concurrency: 'update-stats'

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch: # Allow for running this manually.

jobs:
  update-stats:
    name: repostats
    runs-on: ubuntu-latest
    strategy:
      matrix:
        statsRepo: ['go-gorm/gorm', 'go-gorm/gen', 'go-gorm/gorm.io', 'go-gorm/playground', 'go-gorm/hints', 'go-gorm/datatypes', 'go-gorm/dbresolver', 'go-gorm/sqlite', 'go-gorm/mysql', 'go-gorm/postgres', 'go-gorm/sqlserver', 'go-gorm/clickhouse']
      fail-fast: false
      max-parallel: 1
    steps:
      - name: run-ghrs
        uses: jinzhu/github-repo-stats@v1.3.0
        with:
          repository: ${{ matrix.statsRepo }}
          ghtoken: ${{ secrets.ghrs_github_api_token }}
          databranch: master
